apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 10.164.178.238
    path: /opt/data/vol/0

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-wordpress-mysql-0
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 10.164.178.238
    path: /opt/data/vol/1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-wordpress-mysql-1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 10.164.178.238
    path: /opt/data/vol/2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-wordpress-mysql-2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

