apiVersion: v1
kind: Service
metadata:
  labels:
    name: wordpress
  name: wordpress
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    name: wordpress

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      name: wordpress
    matchExpressions:
      - {key: name, operator: In, values: [wordpress]}
  template:
    metadata:
      labels:
        name: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - mountPath: /var/www/html
          name: my-vol                    
        env:
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass          # generated before in secret.yml
                key: password
          - name: WORDPRESS_DB_HOST
            value: wordpress-mysql
      volumes:
        - name: "my-vol"
          hostPath:
            path: "/mnt/data/web"            
